before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxtst-dev libxcomposite-dev libxrender-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 2
language: perl
perl:
  - "5.8"
  - "5.12"
  - "5.24"

